name: Pull Request Workflow

on:
  push:
    branches:
      - feature-chisom

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated Pull Request"
          title: "Feature Branch Changes"
          body: "Please review and approve these changes."
          branch: master
